services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    env_file:
      - .env.local.backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    env_file:
      - .env.local.backend
    ports:
      - "${EXPOSE_BACKEND_PORT}:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    volumes:
      - php-app-database:/var/lib/mysql/
    ports:
      - "${EXPOSE_DATABASE_PORT}:3306"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    env_file:
      - .env.local.frontend
    volumes:
      - ./frontend/src:/app
      - php-app-frontend-node-modules:/app/node_modules
    ports:
      - "${EXPOSE_FRONTEND_PORT}:3000"
    command: npm run dev

volumes:
  php-app-frontend-node-modules:
  php-app-database:
